version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_SERVER=db
      - DB_USER=sa
      - DB_PASSWORD=123123Abc.
      - DB_NAME=food-api
      - API_KEY=${API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: food-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123123Abc.
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "123456789" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local