version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_SERVER=${DB_SERVER}  # Lấy từ .env
      - DB_USER=sa
      - DB_PASSWORD=${DB_PASSWORD}  # Lấy từ .env
      - DB_NAME=${DB_NAME}  # Lấy từ .env
      - API_KEY=${API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql1
    hostname: sql1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}  # Lấy từ .env
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "123123Abc." -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
